/**
 * Local development fallback ONLY.
 *
 * In production the app reads `/config.json` (generated by `npm run config`
 * from environment variables). If that file is missing or empty, these
 * values are used instead — handy for `ng serve` without a build step.
 */
export const environment = {
  production: false,
  supabaseUrl: '',
  supabaseAnonKey: ''
};
