/**
 * Supabase connection for the browser.
 *
 * At runtime the app first tries to fetch `/config.json` (generated by
 * `npm run config` from host environment variables). If that file is absent or
 * empty — e.g. a host where the build-time env vars weren't set — it falls back
 * to the values below.
 *
 * SAFE TO COMMIT: the URL and the *publishable* (anon) key are public client
 * credentials, gated by Row Level Security. NEVER put the secret / service_role
 * key here — that one only belongs in Edge Function secrets.
 */
export const environment = {
  production: false,
  supabaseUrl: 'https://qehmgeeejcnfsblkrvgq.supabase.co',
  supabaseAnonKey: 'sb_publishable_o_6RnvaSW_gPoKyaZCtoZg_V3fkARMx'
};
